export {Clock} from "./Clock"
export {Greetings} from "./Greetings"
export {MainFocus} from "./MainFocus"
export {Quote} from "./Quote"
export {Weather} from "./Weather"
export {Firefox} from "./Firefox"